import type { PokemonEntry, PokemonType } from "./model";

export const ALL_TYPES: PokemonType[] = [
  "ノーマル", "ほのお", "みず", "でんき", "くさ", "こおり", "かくとう", "どく", "じめん",
  "ひこう", "エスパー", "むし", "いわ", "ゴースト", "ドラゴン", "あく", "はがね", "フェアリー",
];

export const NATURES = [
  "いじっぱり", "ひかえめ", "ようき", "おくびょう", "わんぱく", "ずぶとい",
  "しんちょう", "おだやか", "ゆうかん", "れいせい", "まじめ",
];

const POKEDEX_DATA: PokemonEntry[] = [
  { id: "venusaur", number: 3, name: "フシギバナ", englishName: "Venusaur", types: ["くさ", "どく"], abilities: ["しんりょく", "ようりょくそ"], stats: { hp: 80, attack: 82, defense: 83, specialAttack: 100, specialDefense: 100, speed: 80 } },
  { id: "charizard", number: 6, name: "リザードン", englishName: "Charizard", types: ["ほのお", "ひこう"], abilities: ["もうか", "サンパワー"], stats: { hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100 } },
  { id: "blastoise", number: 9, name: "カメックス", englishName: "Blastoise", types: ["みず"], abilities: ["げきりゅう", "あめうけざら"], stats: { hp: 79, attack: 83, defense: 100, specialAttack: 85, specialDefense: 105, speed: 78 } },
  { id: "pikachu", number: 25, name: "ピカチュウ", englishName: "Pikachu", types: ["でんき"], abilities: ["せいでんき", "ひらいしん"], stats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 } },
  { id: "gengar", number: 94, name: "ゲンガー", englishName: "Gengar", types: ["ゴースト", "どく"], abilities: ["のろわれボディ"], stats: { hp: 60, attack: 65, defense: 60, specialAttack: 130, specialDefense: 75, speed: 110 } },
  { id: "gyarados", number: 130, name: "ギャラドス", englishName: "Gyarados", types: ["みず", "ひこう"], abilities: ["いかく", "じしんかじょう"], stats: { hp: 95, attack: 125, defense: 79, specialAttack: 60, specialDefense: 100, speed: 81 } },
  { id: "snorlax", number: 143, name: "カビゴン", englishName: "Snorlax", types: ["ノーマル"], abilities: ["めんえき", "あついしぼう", "くいしんぼう"], stats: { hp: 160, attack: 110, defense: 65, specialAttack: 65, specialDefense: 110, speed: 30 } },
  { id: "dragonite", number: 149, name: "カイリュー", englishName: "Dragonite", types: ["ドラゴン", "ひこう"], abilities: ["せいしんりょく", "マルチスケイル"], stats: { hp: 91, attack: 134, defense: 95, specialAttack: 100, specialDefense: 100, speed: 80 } },
  { id: "tyranitar", number: 248, name: "バンギラス", englishName: "Tyranitar", types: ["いわ", "あく"], abilities: ["すなおこし", "きんちょうかん"], stats: { hp: 100, attack: 134, defense: 110, specialAttack: 95, specialDefense: 100, speed: 61 } },
  { id: "blaziken", number: 257, name: "バシャーモ", englishName: "Blaziken", types: ["ほのお", "かくとう"], abilities: ["もうか", "かそく"], stats: { hp: 80, attack: 120, defense: 70, specialAttack: 110, specialDefense: 70, speed: 80 } },
  { id: "gardevoir", number: 282, name: "サーナイト", englishName: "Gardevoir", types: ["エスパー", "フェアリー"], abilities: ["シンクロ", "トレース", "テレパシー"], stats: { hp: 68, attack: 65, defense: 65, specialAttack: 125, specialDefense: 115, speed: 80 } },
  { id: "metagross", number: 376, name: "メタグロス", englishName: "Metagross", types: ["はがね", "エスパー"], abilities: ["クリアボディ", "ライトメタル"], stats: { hp: 80, attack: 135, defense: 130, specialAttack: 95, specialDefense: 90, speed: 70 } },
  { id: "garchomp", number: 445, name: "ガブリアス", englishName: "Garchomp", types: ["ドラゴン", "じめん"], abilities: ["すながくれ", "さめはだ"], stats: { hp: 108, attack: 130, defense: 95, specialAttack: 80, specialDefense: 85, speed: 102 } },
  { id: "rotom-wash", number: 479, name: "ウォッシュロトム", englishName: "Rotom Wash", types: ["でんき", "みず"], abilities: ["ふゆう"], stats: { hp: 50, attack: 65, defense: 107, specialAttack: 105, specialDefense: 107, speed: 86 } },
  { id: "excadrill", number: 530, name: "ドリュウズ", englishName: "Excadrill", types: ["じめん", "はがね"], abilities: ["すなかき", "すなのちから", "かたやぶり"], stats: { hp: 110, attack: 135, defense: 60, specialAttack: 50, specialDefense: 65, speed: 88 } },
  { id: "volcarona", number: 637, name: "ウルガモス", englishName: "Volcarona", types: ["むし", "ほのお"], abilities: ["ほのおのからだ", "むしのしらせ"], stats: { hp: 85, attack: 60, defense: 65, specialAttack: 135, specialDefense: 105, speed: 100 } },
  { id: "greninja", number: 658, name: "ゲッコウガ", englishName: "Greninja", types: ["みず", "あく"], abilities: ["げきりゅう", "へんげんじざい", "きずなへんげ"], stats: { hp: 72, attack: 95, defense: 67, specialAttack: 103, specialDefense: 71, speed: 122 } },
  { id: "mimikyu", number: 778, name: "ミミッキュ", englishName: "Mimikyu", types: ["ゴースト", "フェアリー"], abilities: ["ばけのかわ"], stats: { hp: 55, attack: 90, defense: 80, specialAttack: 50, specialDefense: 105, speed: 96 } },
  { id: "corviknight", number: 823, name: "アーマーガア", englishName: "Corviknight", types: ["ひこう", "はがね"], abilities: ["プレッシャー", "きんちょうかん", "ミラーアーマー"], stats: { hp: 98, attack: 87, defense: 105, specialAttack: 53, specialDefense: 85, speed: 67 } },
  { id: "dragapult", number: 887, name: "ドラパルト", englishName: "Dragapult", types: ["ドラゴン", "ゴースト"], abilities: ["クリアボディ", "すりぬけ", "のろわれボディ"], stats: { hp: 88, attack: 120, defense: 75, specialAttack: 100, specialDefense: 75, speed: 142 } },
  { id: "meowscarada", number: 908, name: "マスカーニャ", englishName: "Meowscarada", types: ["くさ", "あく"], abilities: ["しんりょく", "へんげんじざい"], stats: { hp: 76, attack: 110, defense: 70, specialAttack: 81, specialDefense: 70, speed: 123 } },
  { id: "skeledirge", number: 911, name: "ラウドボーン", englishName: "Skeledirge", types: ["ほのお", "ゴースト"], abilities: ["もうか", "てんねん"], stats: { hp: 104, attack: 75, defense: 100, specialAttack: 110, specialDefense: 75, speed: 66 } },
  { id: "quaquaval", number: 914, name: "ウェーニバル", englishName: "Quaquaval", types: ["みず", "かくとう"], abilities: ["げきりゅう", "じしんかじょう"], stats: { hp: 85, attack: 120, defense: 80, specialAttack: 85, specialDefense: 75, speed: 85 } },
  { id: "garganacl", number: 934, name: "キョジオーン", englishName: "Garganacl", types: ["いわ"], abilities: ["きよめのしお", "がんじょう", "クリアボディ"], stats: { hp: 100, attack: 100, defense: 130, specialAttack: 45, specialDefense: 90, speed: 35 } },
  { id: "palafin", number: 964, name: "イルカマン", englishName: "Palafin", types: ["みず"], abilities: ["マイティチェンジ"], stats: { hp: 100, attack: 70, defense: 72, specialAttack: 53, specialDefense: 62, speed: 100 } },
  { id: "kingambit", number: 983, name: "ドドゲザン", englishName: "Kingambit", types: ["あく", "はがね"], abilities: ["まけんき", "そうだいしょう", "プレッシャー"], stats: { hp: 100, attack: 135, defense: 120, specialAttack: 60, specialDefense: 85, speed: 50 } },
  { id: "gholdengo", number: 1000, name: "サーフゴー", englishName: "Gholdengo", types: ["はがね", "ゴースト"], abilities: ["おうごんのからだ"], stats: { hp: 87, attack: 60, defense: 95, specialAttack: 133, specialDefense: 91, speed: 84 } },
  { id: "great-tusk", number: 984, name: "イダイナキバ", englishName: "Great Tusk", types: ["じめん", "かくとう"], abilities: ["こだいかっせい"], stats: { hp: 115, attack: 131, defense: 131, specialAttack: 53, specialDefense: 53, speed: 87 } },
  { id: "flutter-mane", number: 987, name: "ハバタクカミ", englishName: "Flutter Mane", types: ["ゴースト", "フェアリー"], abilities: ["こだいかっせい"], stats: { hp: 55, attack: 55, defense: 55, specialAttack: 135, specialDefense: 135, speed: 135 } },
  { id: "iron-valiant", number: 1006, name: "テツノブジン", englishName: "Iron Valiant", types: ["フェアリー", "かくとう"], abilities: ["クォークチャージ"], stats: { hp: 74, attack: 130, defense: 90, specialAttack: 120, specialDefense: 60, speed: 116 } },
  { id: "ogerpon", number: 1017, name: "オーガポン", englishName: "Ogerpon", types: ["くさ"], abilities: ["まけんき"], stats: { hp: 80, attack: 120, defense: 84, specialAttack: 60, specialDefense: 96, speed: 110 } },
  { id: "alakazam", number: 65, name: "フーディン", englishName: "Alakazam", types: ["エスパー"], abilities: ["シンクロ", "せいしんりょく", "マジックガード"], stats: { hp: 55, attack: 50, defense: 45, specialAttack: 135, specialDefense: 95, speed: 120 } },
  { id: "machamp", number: 68, name: "カイリキー", englishName: "Machamp", types: ["かくとう"], abilities: ["こんじょう", "ノーガード", "ふくつのこころ"], stats: { hp: 90, attack: 130, defense: 80, specialAttack: 65, specialDefense: 85, speed: 55 } },
  { id: "slowbro", number: 80, name: "ヤドラン", englishName: "Slowbro", types: ["みず", "エスパー"], abilities: ["どんかん", "マイペース", "さいせいりょく"], stats: { hp: 95, attack: 75, defense: 110, specialAttack: 100, specialDefense: 80, speed: 30 } },
  { id: "chansey", number: 113, name: "ラッキー", englishName: "Chansey", types: ["ノーマル"], abilities: ["しぜんかいふく", "てんのめぐみ", "いやしのこころ"], stats: { hp: 250, attack: 5, defense: 5, specialAttack: 35, specialDefense: 105, speed: 50 } },
  { id: "starmie", number: 121, name: "スターミー", englishName: "Starmie", types: ["みず", "エスパー"], abilities: ["はっこう", "しぜんかいふく", "アナライズ"], stats: { hp: 60, attack: 75, defense: 85, specialAttack: 100, specialDefense: 85, speed: 115 } },
  { id: "jolteon", number: 135, name: "サンダース", englishName: "Jolteon", types: ["でんき"], abilities: ["ちくでん", "はやあし"], stats: { hp: 65, attack: 65, defense: 60, specialAttack: 110, specialDefense: 95, speed: 130 } },
  { id: "azumarill", number: 184, name: "マリルリ", englishName: "Azumarill", types: ["みず", "フェアリー"], abilities: ["あついしぼう", "ちからもち", "そうしょく"], stats: { hp: 100, attack: 50, defense: 80, specialAttack: 60, specialDefense: 80, speed: 50 } },
  { id: "scizor", number: 212, name: "ハッサム", englishName: "Scizor", types: ["むし", "はがね"], abilities: ["むしのしらせ", "テクニシャン", "ライトメタル"], stats: { hp: 70, attack: 130, defense: 100, specialAttack: 55, specialDefense: 80, speed: 65 } },
  { id: "skarmory", number: 227, name: "エアームド", englishName: "Skarmory", types: ["はがね", "ひこう"], abilities: ["するどいめ", "がんじょう", "くだけるよろい"], stats: { hp: 65, attack: 80, defense: 140, specialAttack: 40, specialDefense: 70, speed: 70 } },
  { id: "swampert", number: 260, name: "ラグラージ", englishName: "Swampert", types: ["みず", "じめん"], abilities: ["げきりゅう", "しめりけ"], stats: { hp: 100, attack: 110, defense: 90, specialAttack: 85, specialDefense: 90, speed: 60 } },
  { id: "breloom", number: 286, name: "キノガッサ", englishName: "Breloom", types: ["くさ", "かくとう"], abilities: ["ほうし", "ポイズンヒール", "テクニシャン"], stats: { hp: 60, attack: 130, defense: 80, specialAttack: 60, specialDefense: 60, speed: 70 } },
  { id: "salamence", number: 373, name: "ボーマンダ", englishName: "Salamence", types: ["ドラゴン", "ひこう"], abilities: ["いかく", "じしんかじょう"], stats: { hp: 95, attack: 135, defense: 80, specialAttack: 110, specialDefense: 80, speed: 100 } },
  { id: "infernape", number: 392, name: "ゴウカザル", englishName: "Infernape", types: ["ほのお", "かくとう"], abilities: ["もうか", "てつのこぶし"], stats: { hp: 76, attack: 104, defense: 71, specialAttack: 104, specialDefense: 71, speed: 108 } },
  { id: "togekiss", number: 468, name: "トゲキッス", englishName: "Togekiss", types: ["フェアリー", "ひこう"], abilities: ["はりきり", "てんのめぐみ", "きょううん"], stats: { hp: 85, attack: 50, defense: 95, specialAttack: 120, specialDefense: 115, speed: 80 } },
  { id: "gliscor", number: 472, name: "グライオン", englishName: "Gliscor", types: ["じめん", "ひこう"], abilities: ["かいりきバサミ", "すながくれ", "ポイズンヒール"], stats: { hp: 75, attack: 95, defense: 125, specialAttack: 45, specialDefense: 75, speed: 95 } },
  { id: "heatran", number: 485, name: "ヒードラン", englishName: "Heatran", types: ["ほのお", "はがね"], abilities: ["もらいび", "ほのおのからだ"], stats: { hp: 91, attack: 90, defense: 106, specialAttack: 130, specialDefense: 106, speed: 77 } },
  { id: "cresselia", number: 488, name: "クレセリア", englishName: "Cresselia", types: ["エスパー"], abilities: ["ふゆう"], stats: { hp: 120, attack: 70, defense: 110, specialAttack: 75, specialDefense: 120, speed: 85 } },
  { id: "ferrothorn", number: 598, name: "ナットレイ", englishName: "Ferrothorn", types: ["くさ", "はがね"], abilities: ["てつのトゲ", "きけんよち"], stats: { hp: 74, attack: 94, defense: 131, specialAttack: 54, specialDefense: 116, speed: 20 } },
  { id: "hydreigon", number: 635, name: "サザンドラ", englishName: "Hydreigon", types: ["あく", "ドラゴン"], abilities: ["ふゆう"], stats: { hp: 92, attack: 105, defense: 90, specialAttack: 125, specialDefense: 90, speed: 98 } },
  { id: "aegislash", number: 681, name: "ギルガルド", englishName: "Aegislash", types: ["はがね", "ゴースト"], abilities: ["バトルスイッチ"], stats: { hp: 60, attack: 50, defense: 140, specialAttack: 50, specialDefense: 140, speed: 60 } },
  { id: "toxapex", number: 748, name: "ドヒドイデ", englishName: "Toxapex", types: ["どく", "みず"], abilities: ["ひとでなし", "じゅうなん", "さいせいりょく"], stats: { hp: 50, attack: 63, defense: 152, specialAttack: 53, specialDefense: 142, speed: 35 } },
  { id: "tapu-koko", number: 785, name: "カプ・コケコ", englishName: "Tapu Koko", types: ["でんき", "フェアリー"], abilities: ["エレキメイカー", "テレパシー"], stats: { hp: 70, attack: 115, defense: 85, specialAttack: 95, specialDefense: 75, speed: 130 } },
  { id: "tapu-fini", number: 788, name: "カプ・レヒレ", englishName: "Tapu Fini", types: ["みず", "フェアリー"], abilities: ["ミストメイカー", "テレパシー"], stats: { hp: 70, attack: 75, defense: 115, specialAttack: 95, specialDefense: 130, speed: 85 } },
  { id: "rillaboom", number: 812, name: "ゴリランダー", englishName: "Rillaboom", types: ["くさ"], abilities: ["しんりょく", "グラスメイカー"], stats: { hp: 100, attack: 125, defense: 90, specialAttack: 60, specialDefense: 70, speed: 85 } },
  { id: "cinderace", number: 815, name: "エースバーン", englishName: "Cinderace", types: ["ほのお"], abilities: ["もうか", "リベロ"], stats: { hp: 80, attack: 116, defense: 75, specialAttack: 65, specialDefense: 75, speed: 119 } },
  { id: "urshifu-rapid-strike", number: 892, name: "ウーラオス（れんげき）", englishName: "Urshifu Rapid Strike", types: ["かくとう", "みず"], abilities: ["ふかしのこぶし"], stats: { hp: 100, attack: 130, defense: 100, specialAttack: 63, specialDefense: 60, speed: 97 } },
  { id: "ursaluna", number: 901, name: "ガチグマ", englishName: "Ursaluna", types: ["じめん", "ノーマル"], abilities: ["こんじょう", "ぼうだん", "きんちょうかん"], stats: { hp: 130, attack: 140, defense: 105, specialAttack: 45, specialDefense: 80, speed: 50 } },
  { id: "sneasler", number: 903, name: "オオニューラ", englishName: "Sneasler", types: ["かくとう", "どく"], abilities: ["プレッシャー", "かるわざ", "どくしゅ"], stats: { hp: 80, attack: 130, defense: 60, specialAttack: 40, specialDefense: 80, speed: 120 } },
  { id: "dondozo", number: 977, name: "ヘイラッシャ", englishName: "Dondozo", types: ["みず"], abilities: ["てんねん", "どんかん", "みずのベール"], stats: { hp: 150, attack: 100, defense: 115, specialAttack: 65, specialDefense: 65, speed: 35 } },
  { id: "tatsugiri", number: 978, name: "シャリタツ", englishName: "Tatsugiri", types: ["ドラゴン", "みず"], abilities: ["しれいとう", "よびみず"], stats: { hp: 68, attack: 50, defense: 60, specialAttack: 120, specialDefense: 95, speed: 82 } },
  { id: "annihilape", number: 979, name: "コノヨザル", englishName: "Annihilape", types: ["かくとう", "ゴースト"], abilities: ["やるき", "せいしんりょく", "まけんき"], stats: { hp: 110, attack: 115, defense: 80, specialAttack: 50, specialDefense: 90, speed: 90 } },
  { id: "clodsire", number: 980, name: "ドオー", englishName: "Clodsire", types: ["どく", "じめん"], abilities: ["どくのトゲ", "ちょすい", "てんねん"], stats: { hp: 130, attack: 75, defense: 60, specialAttack: 45, specialDefense: 100, speed: 20 } },
  { id: "iron-bundle", number: 991, name: "テツノツツミ", englishName: "Iron Bundle", types: ["こおり", "みず"], abilities: ["クォークチャージ"], stats: { hp: 56, attack: 80, defense: 114, specialAttack: 124, specialDefense: 60, speed: 136 } },
  { id: "iron-hands", number: 992, name: "テツノカイナ", englishName: "Iron Hands", types: ["かくとう", "でんき"], abilities: ["クォークチャージ"], stats: { hp: 154, attack: 140, defense: 108, specialAttack: 50, specialDefense: 68, speed: 50 } },
  { id: "baxcalibur", number: 998, name: "セグレイブ", englishName: "Baxcalibur", types: ["ドラゴン", "こおり"], abilities: ["ねつこうかん", "アイスボディ"], stats: { hp: 115, attack: 145, defense: 92, specialAttack: 75, specialDefense: 86, speed: 87 } },
  { id: "chien-pao", number: 1002, name: "パオジアン", englishName: "Chien-Pao", types: ["あく", "こおり"], abilities: ["わざわいのつるぎ"], stats: { hp: 80, attack: 120, defense: 80, specialAttack: 90, specialDefense: 65, speed: 135 } },
  { id: "ting-lu", number: 1003, name: "ディンルー", englishName: "Ting-Lu", types: ["あく", "じめん"], abilities: ["わざわいのうつわ"], stats: { hp: 155, attack: 110, defense: 125, specialAttack: 55, specialDefense: 80, speed: 45 } },
  { id: "chi-yu", number: 1004, name: "イーユイ", englishName: "Chi-Yu", types: ["あく", "ほのお"], abilities: ["わざわいのたま"], stats: { hp: 55, attack: 80, defense: 80, specialAttack: 135, specialDefense: 120, speed: 100 } },
  { id: "roaring-moon", number: 1005, name: "トドロクツキ", englishName: "Roaring Moon", types: ["ドラゴン", "あく"], abilities: ["こだいかっせい"], stats: { hp: 105, attack: 139, defense: 71, specialAttack: 55, specialDefense: 101, speed: 119 } },
  { id: "walking-wake", number: 1009, name: "ウネルミナモ", englishName: "Walking Wake", types: ["みず", "ドラゴン"], abilities: ["こだいかっせい"], stats: { hp: 99, attack: 83, defense: 91, specialAttack: 125, specialDefense: 83, speed: 109 } },
  { id: "archaludon", number: 1018, name: "ブリジュラス", englishName: "Archaludon", types: ["はがね", "ドラゴン"], abilities: ["じきゅうりょく", "がんじょう", "すじがねいり"], stats: { hp: 90, attack: 105, defense: 130, specialAttack: 125, specialDefense: 65, speed: 85 } },
  { id: "raging-bolt", number: 1021, name: "タケルライコ", englishName: "Raging Bolt", types: ["でんき", "ドラゴン"], abilities: ["こだいかっせい"], stats: { hp: 125, attack: 73, defense: 91, specialAttack: 137, specialDefense: 89, speed: 75 } },
  { id: "ursaluna-bloodmoon", number: 1023, name: "ガチグマ（アカツキ）", englishName: "Ursaluna Bloodmoon", types: ["じめん", "ノーマル"], abilities: ["しんがん"], stats: { hp: 113, attack: 70, defense: 120, specialAttack: 135, specialDefense: 65, speed: 52 } },
  { id: "terapagos", number: 1024, name: "テラパゴス", englishName: "Terapagos", types: ["ノーマル"], abilities: ["テラスチェンジ"], stats: { hp: 90, attack: 65, defense: 85, specialAttack: 65, specialDefense: 85, speed: 60 } },
  { id: "pecharunt", number: 1025, name: "モモワロウ", englishName: "Pecharunt", types: ["どく", "ゴースト"], abilities: ["どくくぐつ"], stats: { hp: 88, attack: 88, defense: 160, specialAttack: 88, specialDefense: 88, speed: 88 } },
];

export const POKEDEX = [...POKEDEX_DATA].sort((first, second) => first.number - second.number);
