import type { PokemonEntry, PokemonType } from "./model";

export const ALL_TYPES: PokemonType[] = [
  "ノーマル",
  "ほのお",
  "みず",
  "でんき",
  "くさ",
  "こおり",
  "かくとう",
  "どく",
  "じめん",
  "ひこう",
  "エスパー",
  "むし",
  "いわ",
  "ゴースト",
  "ドラゴン",
  "あく",
  "はがね",
  "フェアリー",
];

export const NATURES = [
  "いじっぱり",
  "ひかえめ",
  "ようき",
  "おくびょう",
  "わんぱく",
  "ずぶとい",
  "しんちょう",
  "おだやか",
  "ゆうかん",
  "れいせい",
  "まじめ",
];

export const POKEDEX: PokemonEntry[] = [
  { id: "venusaur", number: 3, name: "フシギバナ", englishName: "Venusaur", types: ["くさ", "どく"], abilities: ["しんりょく", "ようりょくそ"], stats: { hp: 80, attack: 82, defense: 83, specialAttack: 100, specialDefense: 100, speed: 80 } },
  { id: "charizard", number: 6, name: "リザードン", englishName: "Charizard", types: ["ほのお", "ひこう"], abilities: ["もうか", "サンパワー"], stats: { hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100 } },
  { id: "blastoise", number: 9, name: "カメックス", englishName: "Blastoise", types: ["みず"], abilities: ["げきりゅう", "あめうけざら"], stats: { hp: 79, attack: 83, defense: 100, specialAttack: 85, specialDefense: 105, speed: 78 } },
  { id: "pikachu", number: 25, name: "ピカチュウ", englishName: "Pikachu", types: ["でんき"], abilities: ["せいでんき", "ひらいしん"], stats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 } },
  { id: "gengar", number: 94, name: "ゲンガー", englishName: "Gengar", types: ["ゴースト", "どく"], abilities: ["のろわれボディ"], stats: { hp: 60, attack: 65, defense: 60, specialAttack: 130, specialDefense: 75, speed: 110 } },
  { id: "gyarados", number: 130, name: "ギャラドス", englishName: "Gyarados", types: ["みず", "ひこう"], abilities: ["いかく", "じしんかじょう"], stats: { hp: 95, attack: 125, defense: 79, specialAttack: 60, specialDefense: 100, speed: 81 } },
  { id: "snorlax", number: 143, name: "カビゴン", englishName: "Snorlax", types: ["ノーマル"], abilities: ["めんえき", "あついしぼう", "くいしんぼう"], stats: { hp: 160, attack: 110, defense: 65, specialAttack: 65, specialDefense: 110, speed: 30 } },
  { id: "dragonite", number: 149, name: "カイリュー", englishName: "Dragonite", types: ["ドラゴン", "ひこう"], abilities: ["せいしんりょく", "マルチスケイル"], stats: { hp: 91, attack: 134, defense: 95, specialAttack: 100, specialDefense: 100, speed: 80 } },
  { id: "tyranitar", number: 248, name: "バンギラス", englishName: "Tyranitar", types: ["いわ", "あく"], abilities: ["すなおこし", "きんちょうかん"], stats: { hp: 100, attack: 134, defense: 110, specialAttack: 95, specialDefense: 100, speed: 61 } },
  { id: "blaziken", number: 257, name: "バシャーモ", englishName: "Blaziken", types: ["ほのお", "かくとう"], abilities: ["もうか", "かそく"], stats: { hp: 80, attack: 120, defense: 70, specialAttack: 110, specialDefense: 70, speed: 80 } },
  { id: "gardevoir", number: 282, name: "サーナイト", englishName: "Gardevoir", types: ["エスパー", "フェアリー"], abilities: ["シンクロ", "トレース", "テレパシー"], stats: { hp: 68, attack: 65, defense: 65, specialAttack: 125, specialDefense: 115, speed: 80 } },
  { id: "metagross", number: 376, name: "メタグロス", englishName: "Metagross", types: ["はがね", "エスパー"], abilities: ["クリアボディ", "ライトメタル"], stats: { hp: 80, attack: 135, defense: 130, specialAttack: 95, specialDefense: 90, speed: 70 } },
  { id: "garchomp", number: 445, name: "ガブリアス", englishName: "Garchomp", types: ["ドラゴン", "じめん"], abilities: ["すながくれ", "さめはだ"], stats: { hp: 108, attack: 130, defense: 95, specialAttack: 80, specialDefense: 85, speed: 102 } },
  { id: "rotom-wash", number: 479, name: "ウォッシュロトム", englishName: "Rotom Wash", types: ["でんき", "みず"], abilities: ["ふゆう"], stats: { hp: 50, attack: 65, defense: 107, specialAttack: 105, specialDefense: 107, speed: 86 } },
  { id: "excadrill", number: 530, name: "ドリュウズ", englishName: "Excadrill", types: ["じめん", "はがね"], abilities: ["すなかき", "すなのちから", "かたやぶり"], stats: { hp: 110, attack: 135, defense: 60, specialAttack: 50, specialDefense: 65, speed: 88 } },
  { id: "volcarona", number: 637, name: "ウルガモス", englishName: "Volcarona", types: ["むし", "ほのお"], abilities: ["ほのおのからだ", "むしのしらせ"], stats: { hp: 85, attack: 60, defense: 65, specialAttack: 135, specialDefense: 105, speed: 100 } },
  { id: "greninja", number: 658, name: "ゲッコウガ", englishName: "Greninja", types: ["みず", "あく"], abilities: ["げきりゅう", "へんげんじざい", "きずなへんげ"], stats: { hp: 72, attack: 95, defense: 67, specialAttack: 103, specialDefense: 71, speed: 122 } },
  { id: "mimikyu", number: 778, name: "ミミッキュ", englishName: "Mimikyu", types: ["ゴースト", "フェアリー"], abilities: ["ばけのかわ"], stats: { hp: 55, attack: 90, defense: 80, specialAttack: 50, specialDefense: 105, speed: 96 } },
  { id: "corviknight", number: 823, name: "アーマーガア", englishName: "Corviknight", types: ["ひこう", "はがね"], abilities: ["プレッシャー", "きんちょうかん", "ミラーアーマー"], stats: { hp: 98, attack: 87, defense: 105, specialAttack: 53, specialDefense: 85, speed: 67 } },
  { id: "dragapult", number: 887, name: "ドラパルト", englishName: "Dragapult", types: ["ドラゴン", "ゴースト"], abilities: ["クリアボディ", "すりぬけ", "のろわれボディ"], stats: { hp: 88, attack: 120, defense: 75, specialAttack: 100, specialDefense: 75, speed: 142 } },
  { id: "meowscarada", number: 908, name: "マスカーニャ", englishName: "Meowscarada", types: ["くさ", "あく"], abilities: ["しんりょく", "へんげんじざい"], stats: { hp: 76, attack: 110, defense: 70, specialAttack: 81, specialDefense: 70, speed: 123 } },
  { id: "skeledirge", number: 911, name: "ラウドボーン", englishName: "Skeledirge", types: ["ほのお", "ゴースト"], abilities: ["もうか", "てんねん"], stats: { hp: 104, attack: 75, defense: 100, specialAttack: 110, specialDefense: 75, speed: 66 } },
  { id: "quaquaval", number: 914, name: "ウェーニバル", englishName: "Quaquaval", types: ["みず", "かくとう"], abilities: ["げきりゅう", "じしんかじょう"], stats: { hp: 85, attack: 120, defense: 80, specialAttack: 85, specialDefense: 75, speed: 85 } },
  { id: "garganacl", number: 934, name: "キョジオーン", englishName: "Garganacl", types: ["いわ"], abilities: ["きよめのしお", "がんじょう", "クリアボディ"], stats: { hp: 100, attack: 100, defense: 130, specialAttack: 45, specialDefense: 90, speed: 35 } },
  { id: "palafin", number: 964, name: "イルカマン", englishName: "Palafin", types: ["みず"], abilities: ["マイティチェンジ"], stats: { hp: 100, attack: 70, defense: 72, specialAttack: 53, specialDefense: 62, speed: 100 } },
  { id: "kingambit", number: 983, name: "ドドゲザン", englishName: "Kingambit", types: ["あく", "はがね"], abilities: ["まけんき", "そうだいしょう", "プレッシャー"], stats: { hp: 100, attack: 135, defense: 120, specialAttack: 60, specialDefense: 85, speed: 50 } },
  { id: "gholdengo", number: 1000, name: "サーフゴー", englishName: "Gholdengo", types: ["はがね", "ゴースト"], abilities: ["おうごんのからだ"], stats: { hp: 87, attack: 60, defense: 95, specialAttack: 133, specialDefense: 91, speed: 84 } },
  { id: "great-tusk", number: 984, name: "イダイナキバ", englishName: "Great Tusk", types: ["じめん", "かくとう"], abilities: ["こだいかっせい"], stats: { hp: 115, attack: 131, defense: 131, specialAttack: 53, specialDefense: 53, speed: 87 } },
  { id: "flutter-mane", number: 987, name: "ハバタクカミ", englishName: "Flutter Mane", types: ["ゴースト", "フェアリー"], abilities: ["こだいかっせい"], stats: { hp: 55, attack: 55, defense: 55, specialAttack: 135, specialDefense: 135, speed: 135 } },
  { id: "iron-valiant", number: 1006, name: "テツノブジン", englishName: "Iron Valiant", types: ["フェアリー", "かくとう"], abilities: ["クォークチャージ"], stats: { hp: 74, attack: 130, defense: 90, specialAttack: 120, specialDefense: 60, speed: 116 } },
  { id: "ogerpon", number: 1017, name: "オーガポン", englishName: "Ogerpon", types: ["くさ"], abilities: ["まけんき"], stats: { hp: 80, attack: 120, defense: 84, specialAttack: 60, specialDefense: 96, speed: 110 } },
];
